---
engines:
  rubocop:
    exclude_paths:
      - "config/test.yml"
    base_sub_dir: "test/baseDir"
  duplication:
    exclude_paths:
      - "config/test.yml"
    config:
      languages:
        - "ruby"
languages:
  css:
    extensions:
      - ".scss"
  python:
    enabled: false
exclude_paths:
  - ".bundle/**"
  - "spec/**/*"
  - "benchmarks/**/*"
  - "**.min.js"
  - "**/tests/**"
  - "packages/**"
  - "remix-app/**"
  - "remix.init"
  - "apps/remix-app/**"

include_paths:
  - "**/tests/integration/**"