[phases.setup]
nixPkgs = ["nodejs", "pnpm"]
cacheDirectories = [
  "node_modules",
  ".pnpm-store",
  ".turbo"
]

[phases.install]
cmds = [
  "cd /app",
  "pnpm install --frozen-lockfile --filter=express-backend --filter=@exam-notifier/database"
]

[phases.build]
cmds = [
  "cd /app/packages/database && NODE_OPTIONS='--max-old-space-size=2048' pnpm prisma generate",
  "cd /app && pnpm turbo run build --filter=express-backend --filter=@exam-notifier/database"
]

[start]
cmd = "cd /app/apps/express-backend && node dist/index.js"

[build]
memory = "2GB" 