[phases.setup]
nixPkgs = ["nodejs", "pnpm"]

[phases.install]
cmds = ["pnpm install --no-frozen-lockfile --filter=express-backend --filter=@exam-notifier/database"]

[phases.build]
cmds = ["cd apps/express-backend && pnpm build"]

[start]
cmd = "cd apps/express-backend && cross-env NODE_ENV=production PORT=$PORT pnpm start" 