[phases.setup]
nixPkgs = ["nodejs", "pnpm"]

[phases.install]
cmds = ["pnpm install --no-frozen-lockfile"]

[phases.build]
cmds = ["pnpm build --filter=express-backend"]

[start]
cmd = "cd apps/express-backend && pnpm start" 