[build]
builder = "nixpacks"
buildCommand = "pnpm install --frozen-lockfile && pnpm build --filter=express-backend"

[deploy]
startCommand = "cd apps/express-backend && pnpm start"

[watch]
paths = ["apps/express-backend/**"] 